added funcition to remove events without enough people
greensebastian/socialight pull request #6
Opened 2022-09-19 09:28 UTC by CecilieLindberg

2022-09-19 09:29 UTC, CecilieLindberg commented on src/services/planningService.ts
> +import { IStateRepository } from '../core/interface';
Jeg ved ikke hvorfor jeg blev nød til at ændre stien, men den gamle kunne den ikke finde

2022-09-25 09:19 UTC, greensebastian commented on src/services/planningService.ts
> +import { IStateRepository } from '../core/interface';
Det er noget med hvordan ts-node og tsc aliases virker. Tror det er fikset i master, men det ser vi lige om lidt :)

2022-09-25 09:24 UTC, greensebastian commented on src/services/schedulingService.ts
> +        this.planningService.removeSingleEvent(event);
Should this be awaited?

2022-09-25 09:27 UTC, greensebastian commented on src/services/schedulingService.ts
> +        await this.slackService.sendFailedEventNotification(event);
Since we now may have individuals with open invites, should we expand this function to also send individual messages to them?

2022-09-25 09:29 UTC, greensebastian requested changes
Generally looks good, I think the await for removing single event probably needs fixing, but other than that the comments are all optional 👍

2022-09-26 12:26 UTC, CecilieLindberg commented on src/services/schedulingService.ts
> +        this.planningService.removeSingleEvent(event);
It should I have added it now

2022-10-05 17:24 UTC, greensebastian approved these changes

2022-10-05 17:51 UTC, merged